-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aep_events
(
    event_id integer NOT NULL,
    eventstatus character varying(50) NOT NULL,
    user_id integer,
    PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.aep_policies
(
    contact_id integer NOT NULL,
    current_status character varying(100),
    policy_type character varying(100)
);

CREATE TABLE IF NOT EXISTS public.aep_appointments
(
    id integer NOT NULL,
    event character varying(100) NOT NULL,
    created_time timestamp without time zone NOT NULL,
    contact_id integer NOT NULL,
    event_uuid character varying(36) NOT NULL,
    appointment_time timestamp without time zone NOT NULL,
    event_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.aep_contact
(
    contact_id integer NOT NULL,
    name character varying(100) NOT NULL,
    dob timestamp with time zone,
    PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.aep_users
(
    user_id integer NOT NULL,
    name character varying(100) NOT NULL,
    role character varying(100) NOT NULL,
    PRIMARY KEY (user_id)
);

COMMENT ON COLUMN public.aep_users.role
    IS 'User''s role in the system: agent, manager';

ALTER TABLE IF EXISTS public.aep_events
    ADD FOREIGN KEY (user_id)
    REFERENCES public.aep_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.aep_policies
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.aep_contact (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.aep_appointments
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.aep_contact (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.aep_appointments
    ADD FOREIGN KEY (event_id)
    REFERENCES public.aep_events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;